apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ecom-api-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ecom-api
  minReplicas: 1
  maxReplicas: 28
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
