apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-api
  template:
    metadata:
      labels:
        app: ecom-api
    spec:
      containers:
        - name: ecom-api
          image: ndraaa/ecom-thesis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ecom-db-credentials
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ecom-db-credentials
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ecom-db-credentials
                  key: POSTGRES_DB
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: ecom-api
  labels:
    app: ecom-api
spec:
  selector:
    app: ecom-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
