apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-api
  template:
    metadata:
      labels:
        app: ecom-api
    spec:
      containers:
        - name: ecom-api
          image: ndraaa/ecom-thesis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ecom-db-credentials
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ecom-db-credentials
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ecom-db-credentials
                  key: POSTGRES_DB
          resources:
            requests:
              cpu: "1500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: ecom-api
  labels:
    app: ecom-api
    service: ecom-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: ecom-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP