apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-ecom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: pv-postgres-ecom
