apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-ecom
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/Users/indra/k8s-data/postgres
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
