name: resource-intensive-app-i

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecompass
      POSTGRES_DB: ecomdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecom -d ecomdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
