apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: resource-intensive-api-metrics
  namespace: default
  labels:
    app: kube-prometheus-stack
    release: prometheus
    prometheus: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: resource-intensive
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      scrapeTimeout: 3s
